### DISCUSSION TITLE
Trying to load config file -> daemon.go:41 ▶ DEBUG Config file: /etc/chadburn.conf not found

### DISCUSSION THREAD

**Discussion by mpfl** [PremoWeb/chadburn#18] [Q&A] [answered]
Hi. I like the idea of Chadburn. I've got it running through a docker socker proxy but I'm struggling to configure it for mail.

I have a configuration file at `/home/chadburn/chadburn.conf` and as you can see in my `docker-compose.yml` (at the bottom of this post) it's mapped and chadburn is configured to load the config file.

Unfortunately, on startup I get this in the log:

`daemon.go:41 ▶ DEBUG Config file: /etc/chadburn.conf not found`

Running `docker exec chadburn cat /etc/chadburn.conf` gives me the content of the file.

Anybody got any clues?

```yaml
---
version: "3.5"

services:
  chadburn:
    image: premoweb/chadburn:latest
    container_name: chadburn
    depends_on:
      - docker-socket-proxy
    command: daemon --config=/etc/chadburn.conf
    environment:
      - DOCKER_HOST=tcp://chadburn-docker-socket-proxy:2375
    volumes:
      - /home/chadburn/chadburn.conf:/etc/chadburn.conf
    labels:
      - "diun.enable=true"
    restart: unless-stopped

  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: chadburn-docker-socket-proxy
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - EXEC=1
      - INFO=1
      - POST=1
    restart: unless-stopped
    labels:
      - "diun.enable=true"
```
