### DISCUSSION TITLE
job-run vs job-exec

### DISCUSSION THREAD

**Discussion by s-celles** [PremoWeb/chadburn#74] [Q&A]
Hello,

Following https://github.com/PremoWeb/chadburn/issues/70 ... posting here (expecting some help)

I'd like to run using a docker-compose file a simple script at periodic time interval

I did the following for testing (and compare job-exec and job-run)

```yml
version: "3.8"
services:
  job-scheduler:
    image: premoweb/chadburn:latest
    #depends_on:
    #  - nginx
    command: daemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    #  - ./config.ini:/etc/chadburn.conf
    restart: unless-stopped

  nginx:
    image: nginx
    labels:
      chadburn.enabled: "true"
      chadburn.job-exec.datecron.schedule: "@every 5s"
      chadburn.job-exec.datecron.command: "uname -a"

  alpine:
    image: alpine
    labels:
      chadburn.enabled: "true"
      chadburn.job-run.datecron.schedule: "@every 5s"
      chadburn.job-run.datecron.command: "date +'%Y-%m-%dT%H:%M:%SZ'"
```

with nginx it's working fine as the server is always waiting...(and container is always running) so `job-exec` is appropriate for that purpose

On the other side I want to run `date +'%Y-%m-%dT%H:%M:%SZ` every 5s using alpine image.

In this example I want to run a command inside of a new container, using a specific image so `job-run` seems to be appropriated

but in this example command is only run one time... not every 5 seconds.

I don't understand what I did wrong (I'd prefer not to use config file... just labels in docker-compose)

I wonder if... for alpine example I should really put labels in alpine service or if it should be done on chadburn service.

Some help will be very nice!

Kind regards
