### DISCUSSION TITLE
Does not give notice when there's an error on INI and INI does not support multiple lines.

### DISCUSSION THREAD

**Discussion by trajano** [PremoWeb/chadburn#84] [General]
My INI file.  All I did was put new lines in the `command`.  On the upstream it gives an error saying that that string is not terminated which doesn't appear to be true.  but on the fork it does not even show an error message.

```
[global]

[job-service-run "Do a job at CA1"]
schedule = @every 10s
image = fullstorydev/grpcurl:latest
delete = false

command = """
  grpcurl --plaintext -d {'name':'foo'} ca1:6565 rpc.Greeter/SayHello
"""
```

Docker compose
```yml
version: "3.7"
services:
  scheduler:
    image: ghcr.io/premoweb/chadburn:latest
    command: daemon --config=/jobs.ini
    deploy:
      resources:
        limits:
          memory: 256M
      placement:
        constraints:
          - "node.role == manager"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    configs:
      - source: jobs
        target: /jobs.ini
        mode: 0600
configs:
  jobs:
    file: ./example.ini
```
