### DISCUSSION TITLE
Healthcheck

### DISCUSSION THREAD

**Discussion by ogmueller** [PremoWeb/chadburn#85] [General]
I know, this is a tiny feature request, but would it be possible to add an healthcheck to the container?

It would support the new [startup/shutdown order](https://docs.docker.com/compose/startup-order/), when using [condition with depends_on](https://docs.docker.com/compose/compose-file/05-services/#depends_on).

**Comment by borisdigital** [comment]
I'm sure this is how it's _not_ supposed to be, but i'm using this "quirk" to get a healthy status.
1) enable metrics
2) check for open metrics port via nc (already installed in container image)

compose.yml
```
services:
  chadburn:
    ...
    command: daemon --config=/etc/chadburn.conf --metrics --listen-address=:8080
    healthcheck:
      interval: 10s
      retries: 3
      start_interval: 5s
      start_period: 30s
      test: nc -z localhost:8080 ## check for open metrics port
      timeout: 10s
    ...
```
