### DISCUSSION TITLE
[Feature Request] container startup and teardown job

### DISCUSSION THREAD

**Discussion by martindmtrv** [PremoWeb/chadburn#92] [General]
Since chadburn is able to dynamically pull the Docker configs perhaps there is a new use case where jobs can be ran a single time on startup / shutdown of containers

A simple use case could be a script that on startup sends a notification like "container x started" but we only want to run the script once, not on an interval

There may be a way to do this with Docker compose already (override command / entry point). This feature is different since I'm suggesting that this could be useful for other commands that we don't want to execute from within the container that we just started but on a different container or the host machine

Another reason this is useful is we could essentially define event driven actions (container start, stop, health status change?) directly in Docker compose files which would be pretty sweet for managing stacks in portainer

**Comment by maietta** [comment]
This is a very good feature request.

Docker Events emits start/stop notices for containers, so implementation seems like it might be pretty straightforward.

Assigning a label to designate that something should only run once, would be do-able, but Chadburn could update a label for a service to signal that it has in fact, been run.

Thanks for the suggestion.

**Comment by maietta** [comment]
# Update on Container Lifecycle Jobs Feature

Good news! We've implemented the container startup and teardown job feature you requested and it has been merged into the main branch. This feature will be available in the upcoming release.

## Implementation Details:

- Added support for container lifecycle jobs that run once on container start or stop events
- Jobs can be configured to trigger on either container start or stop events
- Each job runs only once per event (not repeatedly)
- Configuration is done through Docker labels, making it easy to integrate with Portainer or Docker Compose

## Example Usage in Docker Compose:

```yaml
services:
  my-service:
    image: nginx
    labels:
      - "chadburn.job.startup-notification.container=my-service"
      - "chadburn.job.startup-notification.event=start"
      - "chadburn.job.startup-notification.command=curl -X POST https://example.com/webhook -d 'Container my-service started'"
      
      - "chadburn.job.shutdown-notification.container=my-service"
      - "chadburn.job.shutdown-notification.event=stop"
      - "chadburn.job.shutdown-notification.command=curl -X POST https://example.com/webhook -d 'Container my-service stopped'"
```

This implementation allows you to define event-driven actions directly in your Docker Compose files as you suggested. The jobs can execute commands on the host machine or interact with other containers, providing flexibility for various use cases.

Thank you for your valuable feature request! This addition makes Chadburn even more powerful for container orchestration and automation.

The feature will be included in the next release. In the meantime, if you'd like to try it out, you can build from the main branch.
