### DISCUSSION TITLE
"Daemon" command does not bypass looking for a config file

### DISCUSSION THREAD

**Discussion by aefruswg** [PremoWeb/chadburn#94] [General]
I'm trying to use Chadburn to replace an issue I encountered with Ofelia and the container continues to error out that it can't find a config. Trying with docker run and docker compose both result in the same error below

```
docker run -it --rm \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    -v  /path/on/host/chadburn.conf:/tmp/chadburn.conf:ro \
        premoweb/chadburn:latest daemon
```

```
version: '3'
services:
  chadburn-service:
    image: premoweb/chadburn:latest
    container_name: chadburn-service
    command: daemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
```
`daemon.go:48 ▶ DEBUG Cannot read config file: "open /etc/chadburn.conf: no such file or directory"`

[This is also the error I'm encountering with Ofelia, so hopefully it won't be the same with Chadburn](https://github.com/mcuadros/ofelia/issues/234)
