### ISSUE TITLE
Dockerhub Tags

### ISSUE THREAD

**Issue by mnestor** [PremoWeb/chadburn#11]
Could you tag the docker images with version and hashes please?

In reference to #9 since there is only a latest tag we can't pull the v1.0.0 release to get docker label detection working again.

it also makes for following a practice of running containers are a specific version to avoid auto-upgrades.

**Comment by maietta** [comment]
Nice issue request! Agreed, we need this. I only recently started getting more familiar with Github Actions to help me automate as much as possible and so it'll take me a bit to discover just exactly how this is done. I ran into an issue recently with Docker Hub not receiving the built images, so I'm going to be working on this at the same time.

If you know of any open source projects that do this, please let me know so I can take a peek at how they do it, otherwise I'll have to dig around.

For the moment, I am referencing the specific version on the Github Container registry using ghcr.io/premoweb/chadburn:v1.0.0

I'll try to get this setup today.

**Comment by mnestor** [comment]
I can get you close, I do this in my nextcloud-smb build but since it's derived I removed the tags based on git tags.

This is the action to use
https://github.com/marketplace/actions/docker-metadata-action

```
on:
  push:
    tags:
      - 'v*'
    
- name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: itsmetommy/hello-github-actions

- name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

You can take a look at one of mine. I don't have the tags part in since the image I build is derived just to add a feature to the app. You'd need to add the "on/push/tags/v*" part.
https://github.com/mnestor/nextcloud-smb/blob/main/.github/workflows/docker-image.yml#L27

I would have taken a stab at a pr but i wasn't entirely clear on your current tags setup and this would replace that and still get what you have now. Maybe nothing more would need to be added that what I put above though.
