### ISSUE TITLE
Certain jobs fail to register.

### ISSUE THREAD

**Issue by ccarney16** [PremoWeb/chadburn#13]
Hello! I saw your project and looked into migrating over due to support of dynamically adding in cron jobs. However I noticed that upon migrating over, all run jobs and certain exec jobs are not being seen. I largely use container labels to create and run tasks and have taken into account the change in the label prefix (ofelia to chadburn).

These examples tasks are taken from a docker-compose project I maintain on github that currently uses ofelia:

What does work with chadburn:
```
    labels:
      chadburn.enabled: "true"
      chadburn.job-exec.pqueue.schedule: "@every 1m"
      chadburn.job-exec.pqueue.command: "php /var/www/html/artisan schedule:run"
      chadburn.job-exec.pqueue.user: "nginx"
```

What does not work with chadburn:
```
    labels:
      chadburn.enabled: "true"
      chadburn.job-run.le-renew.schedule: "0 0 0 * * *"
      chadburn.job-run.le-renew.container: pterodactyl_certbot_1

    labels:
      chadburn.enabled: "true"
      chadburn.job-exec.daemon-reload.schedule: "${DAEMON_RELOAD_SCHEDULE:-0 30 0 * * *}"
      chadburn.job-exec.daemon-reload.command: "kill -15 1"
```

I am not too sure if there are any additional configuration needed. but any assistance would be appreciated!

Also as a sidenote, would it be possible to omit the container option in run jobs?
