### ISSUE TITLE
Doesn't seem to work in multi-node swarm

### ISSUE THREAD

**Issue by fidelix** [PremoWeb/chadburn#15]
I'm using caprover in cluster mode (multi-node swarm).

Here is the spec for a service:
```
TaskTemplate:
  ContainerSpec:
    Labels:
      chadburn.enabled: "true"
      chadburn.job-exec.drush-cron.command: "drush --uri=https://www.mysite.com cron-run"
      chadburn.job-exec.drush-cron.schedule: "@every 10m"
```

The task is not being executed (or it's erroring out and not showing in the logs).
I tried to set chadburn to run only in a manager node to see if that was the issue, but I got the same results.
