### ISSUE TITLE
Chadburn is not picking up any tasks

### ISSUE THREAD

**Issue by dakky** [PremoWeb/chadburn#46]
### docker-compose chadburn:
```
version: "3"
services:
  chadburn:
    image: premoweb/chadburn:latest
    container_name: chadburn
    restart: always
    command: daemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

    networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik-network
```
### docker-compose influxdb
```
version: '3.7'

services:
  influxdb:
    image: arm64v8/influxdb:2.2
    container_name: influxdb
    restart: always
    labels:
      chadburn.enabled: true
      chadburn.job-exec.backup-influxdb.schedule: "38 8 * * *"
      chadburn.job-exec.backup-influxdb.command: "/backup/backup.sh"
[....]
```
### docker inspect of the container
```
❯ docker inspect influxdb | jq ".[].Config.Labels"
{
  "chadburn.enabled": "True",
  "chadburn.job-exec.backup-influxdb.command": "/backup/backup.sh",
  "chadburn.job-exec.backup-influxdb.schedule": "38 8 * * *",
  "com.docker.compose.config-hash": "5e307b1e77c4fd6682759977b4a9472868ed6d75fd76d30a7492bc328eb5c14d",
  "com.docker.compose.container-number": "1",
  "com.docker.compose.oneoff": "False",
  "com.docker.compose.project": "influxdb2",
  "com.docker.compose.project.config_files": "docker-compose.yaml",
  "com.docker.compose.project.working_dir": "/opt/influxdb2",
  "com.docker.compose.service": "influxdb",
  "com.docker.compose.version": "1.29.2"
}
```

### Logs of chadburn
```
Attaching to chadburn
chadburn    | daemon.go:47 ▶ DEBUG Config file: /etc/chadburn.conf not found
chadburn    | scheduler.go:101 ▶ DEBUG Starting scheduler
chadburn    | cron_utils.go:13 ▶ DEBUG start
```

Do I miss something?
