### ISSUE TITLE
overriding job defaults possible?

### ISSUE THREAD

**Issue by noname77** [PremoWeb/chadburn#48]
Hi,

I am wondering if it's possible to override default job parameter values?

My use case is for setting the user or no-overlap on job-exec once per container vs having to specify it for every job, i.e.

```
    labels:
      chadburn.enabled: "true"
      
      # test task
      chadburn.job-exec.test-job.schedule: '@every 1h'
      chadburn.job-exec.test-job.command: 'bash -lc "python -u -m test_task'
      chadburn.job-exec.test-job.no-overlap: 'true'
      chadburn.job-exec.test-job.user: "non-root"

      # different test task
      chadburn.job-exec.test-job-2.schedule: '@every 2h'
      chadburn.job-exec.test-job-2.command: 'bash -lc "python -u -m test_task_2'
      chadburn.job-exec.test-job-2.no-overlap: 'true'
      chadburn.job-exec.test-job-2.user: "non-root"
```

and im wondering If something like below can be achieved?
```
    labels:
      chadburn.enabled: "true"
      chadburn.default.job-exec.user: "non-root"
      chadburn.default.job-exec.no-overlap: "true"
      
      # test task
      chadburn.job-exec.test-job.schedule: '@every 1h'
      chadburn.job-exec.test-job.command: 'bash -lc "python -u -m test_task'

      # different test task
      chadburn.job-exec.test-job-2.schedule: '@every 2h'
      chadburn.job-exec.test-job-2.command: 'bash -lc "python -u -m test_task_2'
```

thanks!
