### ISSUE TITLE
Chadburn not picking up all tasks defined in config.ini

### ISSUE THREAD

**Issue by vutsalsinghal** [PremoWeb/chadburn#53]
Hi There

Love the project... Appreciate your (@maietta) initiative to carry on after Ofelia!

This is my config.ini

```
[global]
save-folder=/host/logs
save-only-on-error=true


[job-local "calendar_alerts"]
schedule=0 0 0 * * *
command=/host/calendar_alerts.sh
no-overlap=true

[job-local "domain_expiry"]
schedule=0 0 0 * * *
command=/host/domain_expiry.sh
no-overlap=true

[job-local "host_cmds"]
schedule=0 0 1 * * *
command=/host/host_cmds.sh
no-overlap=true

[job-local "code_server_restart"]
schedule=@every 6h
command=/host/code_server_restart.sh
no-overlap=true
```

When I use `mcuadros/ofelia:latest` image, it picks up all 4 tasks but when I use `premoweb/chadburn:latest` image, it picks up only the last task.  There are no other changes except... Any idea?

 I'm on Raspberry pi 4 8GB 64bit OS. My docker-compose is below
 
 ```
 ofelia:
    # image: premoweb/chadburn:latest
    image: mcuadros/ofelia:latest
    container_name: ofelia_container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ofelia:/host
    command: daemon --config=/host/config.ini
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Los_Angeles
    env_file:
      - ./ofelia/.env
    networks:
      - apps_ntwrk
    restart: unless-stopped
 ```
 
 (Another small thing i would like to bring to your attention is, there are no timestamps in Chadburn logs as compared to Ofelia logs)
