### ISSUE TITLE
Multiple projects with chadburn : jobs registered/deregistered loop

### ISSUE THREAD

**Issue by EmmanuelVella** [PremoWeb/chadburn#54]
Hello,

I have a project that I need to deploy multiple times on my staging server, with differents `COMPOSE_PROJECT_NAME`. I noticed that in this case, the jobs are in registered/deregistered loop : 

![image](https://user-images.githubusercontent.com/663607/223855024-71ef1982-d689-4441-8db0-a12fe7b20697.png)

This is easy to reproduce with the project docker-compose example : 

```yaml
version: "3"
services:
  chadburn:
    image: premoweb/chadburn:latest
    depends_on:
      - nginx
    command: daemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx:
    image: nginx
    labels:
      chadburn.enabled: "true"
      chadburn.job-exec.datecron.schedule: "@every 5m"
      chadburn.job-exec.datecron.command: "uname -a"
```

Then in 2 different terminals :

`COMPOSE_PROJECT_NAME=project1 docker compose up`
`COMPOSE_PROJECT_NAME=project2 docker compose up`

I don't know how I can avoid this behavior ! Do you have a hint ?

Thank you !
