### ISSUE TITLE
Job is always being deregistered

### ISSUE THREAD

**Issue by theonelucas** [PremoWeb/chadburn#6]
Hi, it seems that if I use a configuration file instead of the `labels` option in the `docker-compose` file my job is always deregistered for some reason:

```sh
scheduler  | daemon.go:41 ▶ DEBUG Config file: /etc/chadburn.conf not found                                     │
scheduler  | scheduler.go:45 ▶ NOTICE New job registered "users-tasks" - "uname -a" - "@every 20s" - ID: 1      │
scheduler  | scheduler.go:56 ▶ DEBUG Starting scheduler                                                         │
scheduler  | cron_utils.go:13 ▶ DEBUG start                                                                     │
scheduler  | cron_utils.go:13 ▶ DEBUG schedule
scheduler  | scheduler.go:50 ▶ NOTICE Job deregistered (will not fire again) "users-tasks" - "uname -a" - "@ever│
y 20s" - ID: 1                                                                                                  │
scheduler  | cron_utils.go:13 ▶ DEBUG removed
```

My `config.conf`:

```ini
[global]
save-folder = /etc/logs

[job-exec "users-tasks"]
schedule = @every 20s
container = api
network = app-network
command = uname -a
```

My `docker-compose.yml`:

```yml
api:
        image: some-cool-image
        labels:
            chadburn.enabled: "true"

scheduler:
        image: premoweb/chadburn:latest
        container_name: scheduler
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./scheduler/config.conf:/etc/chadburn.conf
        depends_on:
            - api
        networks:
            - app-network
```

But it works if I do this:

```yml
api:
        image: some-cool-image
        labels:
            chadburn.enabled: "true"
            chadburn.job-exec.datecron.schedule: "@every 5s"
            chadburn.job-exec.datecron.command: "uname -a"

scheduler:
        image: premoweb/chadburn:latest
        container_name: scheduler
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        depends_on:
            - api
        networks:
            - app-network
```

**Comment by maietta** [comment]
Interestingly, the /etc/chadburn.conf is not being found when the service is trying to start.

I'm currently working on this. This is what I see from your example:

daemon.go:41 ▶ DEBUG Config file: /etc/chadburn.conf not found

**Comment by maietta** [comment]
Okay, update:

Your config is calling for a container name of "api" but when using docker-compose, Chadburn cannot find this container by the name "api".

I've moved "depends_on" to the API service as it does depend on the operation of the scheduler.

Also, your api container doesn't seem to contain a /etc/logs/ directory, but that in itself wasn't causing the deregistration of the job.

I couldn't create a network name called app-network in my environment, so I omitted that for resting, so my adapted code looks like:

```
version: "3.8"

services:
  api:
    image: php:7.2-apache
    container_name: api
    labels:
        chadburn.enabled: "true"
    depends_on:
      - scheduler
  scheduler:
    image: premoweb/chadburn:latest
    container_name: scheduler
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config.conf:/etc/chadburn.conf
```
config.conf

```
[global]
save-folder = /tmp/

[job-exec "users-tasks"]
schedule = @every 1s
container = api
command = php -v
```

I am still working to resolve this issue.
