### ISSUE TITLE
Merging docker labels and INI settings doesn't work as expected

### ISSUE THREAD

**Issue by ogmueller** [PremoWeb/chadburn#61]
My chadburn ini is as follows:
```ini
[global]
smtp-host=postfix-relay
smtp-port=25
email-to=to@mail.com
email-from=from@mail.com
mail-only-on-error=true
```

These values are pretty good, but sometime, i'd like to overwrite some like the `email-to` and/or `email-from`. But it doesn't really work.

As soon as I overwrite `email-to` AND `email-from`, the other global values as e.g. `smtp-host` or `smtp-port` are also overwritten: 
```yml
chadburn.enabled: "true"
chadburn.job-exec.cron.email-to: "Its me <different-to@mail.com>"
chadburn.job-exec.cron.email-from: "Cron <different-from@mail.com>"
chadburn.job-exec.cron.schedule: "@every 1m"
chadburn.job-exec.cron.command: "php cron.php"
chadburn.job-exec.cron.user: "www-data"
chadburn.job-exec.cron.no-overlap: true
```
So with those labels, email delivery fails, because chadburn is unable to connect to the email server.

When just using these labels:
```yml
chadburn.enabled: "true"
chadburn.job-exec.cron.schedule: "@every 1m"
chadburn.job-exec.cron.command: "php cron.php"
chadburn.job-exec.cron.user: "www-data"
chadburn.job-exec.cron.no-overlap: true
```
everything works fine without connection failures.

My expectation is, that by merging those values, only the ones mentioned in the label will overwrite the ones in the ini file.
